### ISSUE TITLE
data url absolute to https://makingdatavisual.github.io/data

### ISSUE THREAD

**Issue by timelyportfolio** [domoritz/vis-examples#3]
Book is already incredible, and this interactive figure list is amazing.  Happy to submit a pull request.  Can the data urls be absolute so that Vega-editor knows where to find it?  Thanks!!!

![image](https://user-images.githubusercontent.com/837910/35830381-a93ebcfe-0a8b-11e8-964f-2a134b91040c.png)
 instead of

![image](https://user-images.githubusercontent.com/837910/35830428-ce61f8de-0a8b-11e8-91fc-083a4d148a4e.png)

**Comment by danyelf** [comment]
Thanks for the comment.  I've been trying to decide whether to go with absolute URLs -- which is better for vega-editor -- or local URLs, which are better for local repos. @domoritz , any thoughts on that?

Quick question for you: how did you wind up at this site? (The canonical location for them all is at MakingDataVisual.github.io )

**Comment by domoritz** [comment]
I'd rather fix the issue on the embed/editor side: https://github.com/vega/vega-embed/issues/55. I just haven't found the time to do it. @timelyportfolio, do you want to take a stab at it?

**Comment by domoritz** [comment]
Let's track this issue over at https://github.com/MakingDataVisual/makingdatavisual.github.io/issues.

**Comment by domoritz** [comment]
Fixed in the editor.
